flowchart TD
%% generated in 0.00s

    %% Entry points (blue)
    classDef entry fill:#4dabf7,stroke:#1971c2,color:#fff

    subgraph Core
        generated__validator__resolve__taskand__dev__v1__test____dirname["__dirname"]
        generated__validator__resolve__taskand__dev__v1__test__r1["r1"]
        generated__validator__resolve__taskand__dev__v1__test__r2["r2"]
        generated__vault__secrets__taskand__dev__v1__bin__raw["raw"]
        generated__vault__secrets__taskand__dev__v1__bin__act["act"]
        generated__developer__spawn__taskand__dev__v1__bin__raw["raw"]
        generated__developer__spawn__taskand__dev__v1__bin__KEY["KEY"]
        generated__developer__spawn__taskand__dev__v1__bin__org["org"]
        generated__planner__plan__taskand__dev__v1__test____dirname["__dirname"]
        generated__planner__plan__taskand__dev__v1__test__r["r"]
        generated__planner__plan__taskand__dev__v1__test__out["out"]
        generated__web__serve__taskand__dev__v1__bin__action["action"]
        generated__web__serve__taskand__dev__v1__test____dirname["__dirname"]
        generated__web__serve__taskand__dev__v1__test__r["r"]
        generated__web__serve__taskand__dev__v1__test__out["out"]
        ...["+321 more"]
    end

    class generated__validator__resolve__taskand__dev__v1__test____dirname,generated__validator__resolve__taskand__dev__v1__test__r1,generated__validator__resolve__taskand__dev__v1__test__r2,generated__vault__secrets__taskand__dev__v1__bin__raw,generated__vault__secrets__taskand__dev__v1__bin__act,generated__developer__spawn__taskand__dev__v1__bin__raw,generated__developer__spawn__taskand__dev__v1__bin__KEY,generated__developer__spawn__taskand__dev__v1__bin__org,generated__planner__plan__taskand__dev__v1__test____dirname,generated__planner__plan__taskand__dev__v1__test__r entry
